language: generic
sudo: required
services: 
  - docker
  
before-install:
  - docker build -t docker-react -f Dockerfile.dev .  

script:
  - docker run -e CI=true docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "react-docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-232223232"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"    